//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18034
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STA_Viewer_0._1.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STA_Viewer_0._1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap archives {
            get {
                object obj = ResourceManager.GetObject("archives", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cc88x31 {
            get {
                object obj = ResourceManager.GetObject("cc88x31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ccbynd_88x31 {
            get {
                object obj = ResourceManager.GetObject("ccbynd_88x31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Deurschlandkarte_Umrisse {
            get {
                object obj = ResourceManager.GetObject("Deurschlandkarte Umrisse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SDAW&gt;
        ///  &lt;filetype&gt;FRE&lt;/filetype&gt;
        ///  &lt;version&gt;FRE Version 004&lt;/version&gt;
        ///  &lt;myversion&gt;SDAW FRE 1&lt;/myversion&gt;
        ///  &lt;description&gt;
        ///    Meldung freier Stellen (FRE)
        ///    Diese Datei wird zur Übermittlung von Freizahlen verwendet..
        ///  &lt;/description&gt;
        ///  &lt;dataidentifier&gt;D&lt;/dataidentifier&gt;
        ///  &lt;sdawfieldset&gt;
        ///
        ///    &lt;field&gt;
        ///      &lt;title&gt;Satzart&lt;/title&gt;
        ///      &lt;type&gt;Char&lt;/type&gt;
        ///      &lt;startpos&gt;1&lt;/startpos&gt;
        ///      &lt;length&gt;1&lt;/length&gt;
        ///      &lt;description&gt;Datensatz&lt;/description&gt;        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string FRE {
            get {
                return ResourceManager.GetString("FRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Document   : SdawKopfsaetze.xml
        ///    Created on : 9. Juni 2011, 12:48
        ///    Author     : mckoch
        ///    Description:
        ///        Purpose of the document follows.
        ///--&gt;
        ///&lt;SDAW&gt;
        ///  &lt;filetype&gt;FREKOPFSAETZE&lt;/filetype&gt;
        ///  &lt;version&gt;SDAW Version 004&lt;/version&gt;
        ///  &lt;myversion&gt;SDAW 1&lt;/myversion&gt;
        ///  &lt;description&gt;
        ///    Kopfdaten der eingepflegten FRE-Sateien (Freizahlen).
        ///  &lt;/description&gt;
        ///  &lt;dataidentifier&gt;K&lt;/dataidentifier&gt;
        ///  &lt;!--    &lt;mode&gt;REPLACE&lt;/mode&gt;--&gt;
        ///  &lt;sdawfieldset [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string FRE_KOPF {
            get {
                return ResourceManager.GetString("FRE_KOPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SDAW&gt;
        ///  &lt;filetype&gt;STA&lt;/filetype&gt;
        ///  &lt;version&gt;STA Version 004&lt;/version&gt;
        ///  &lt;myversion&gt;SDAW STA 1&lt;/myversion&gt;
        ///  &lt;description&gt;Stammdaten / Stellenbestand (STA): Diese Datei wird zur Meldung des vorhanden Stellenbestandes, der vermarket wird, verwendet.&lt;/description&gt;
        ///  &lt;dataidentifier&gt;D&lt;/dataidentifier&gt;
        ///  &lt;sdawfieldset&gt;
        ///    &lt;!-- field template
        ///		&lt;field&gt;
        ///			&lt;title&gt;&lt;/title&gt;
        ///			&lt;type&gt;&lt;/type&gt;
        ///			&lt;startpos&gt;&lt;/startpos&gt;
        ///			&lt;length&gt;&lt;/length&gt;
        ///			&lt;description&gt;&lt;/descrip [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string STA {
            get {
                return ResourceManager.GetString("STA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Document   : SdawKopfsaetze.xml
        ///    Created on : 9. Juni 2011, 12:48
        ///    Author     : mckoch
        ///    Description:
        ///        Purpose of the document follows.
        ///--&gt;
        ///&lt;SDAW&gt;
        ///  &lt;filetype&gt;STAKOPFSAETZE&lt;/filetype&gt;
        ///  &lt;version&gt;SDAW Version 004&lt;/version&gt;
        ///  &lt;myversion&gt;SDAW 1&lt;/myversion&gt;
        ///  &lt;description&gt;
        ///    Kopfdaten der eingepflegten Dateien. Zur Versionierung STA, VMS, FRE.
        ///  &lt;/description&gt;
        ///  &lt;dataidentifier&gt;K&lt;/dataidentifier&gt;
        ///  &lt;!--    &lt;mode&gt;REPLACE&lt;/mode&gt;--&gt;        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string STA_KOPF {
            get {
                return ResourceManager.GetString("STA_KOPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unbenannt_1 {
            get {
                object obj = ResourceManager.GetObject("Unbenannt-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;!--
        ///    Document   : VMS.xml
        ///    Created on : 1. Mai 2011, 18:29
        ///    Author     : mckoch
        ///    Description:
        ///        Purpose of the document follows.
        ///--&gt;
        ///
        ///&lt;SDAW&gt;
        ///  &lt;filetype&gt;VMS&lt;/filetype&gt;
        ///  &lt;version&gt;VMS Version 004&lt;/version&gt;
        ///  &lt;myversion&gt;SDAW VMS 1&lt;/myversion&gt;
        ///  &lt;description&gt;
        ///    Stammdaten Verbrauchermarkt-Stammdaten, die von einem Anbieter verwendet
        ///    werden.(Verbrauchermarkt-Skizzen: siehe Anhang C 14)
        ///  &lt;/description&gt;
        ///  &lt;dataidentifier&gt;D&lt;/datai [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string VMS {
            get {
                return ResourceManager.GetString("VMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;!--
        ///    Document   : SdawKopfsaetze.xml
        ///    Created on : 9. Juni 2011, 12:48
        ///    Author     : mckoch
        ///    Description:
        ///        Purpose of the document follows.
        ///--&gt;
        ///&lt;SDAW&gt;
        ///  &lt;filetype&gt;VMSKOPFSAETZE&lt;/filetype&gt;
        ///  &lt;version&gt;VMS Version 004&lt;/version&gt;
        ///  &lt;myversion&gt;SDAW 1&lt;/myversion&gt;
        ///  &lt;description&gt;
        ///    Kopfdaten der eingepflegten VMS-Dateien (Verbrauchermart-Stammdaten
        ///  &lt;/description&gt;
        ///  &lt;dataidentifier&gt;K&lt;/dataidentifier&gt;
        ///  &lt;!--    &lt;mode&gt;REPLACE&lt;/mode&gt;--&gt;
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string VMS_KOPF {
            get {
                return ResourceManager.GetString("VMS_KOPF", resourceCulture);
            }
        }
    }
}
